type: confdb-schema
authority-id: <YOUR_ACCOUNT_ID>
account-id: <YOUR_ACCOUNT_ID>
name: cpu-stats
revision: "6"
timestamp: <TIMESTAMP>
# TODO Can I make this read-only since it's moving to ephemeral?
views:
  monitor:
    rules:
      - request: "data.{field}"
        storage: "stats.{field}"
        access: read-write
body: |-
  {
    "storage": {
      "schema": {
        "stats": {
          "schema": {
            "utilization": {
              "type": "string",
              "ephemeral": true
            },
            "last-updated": {
              "type": "string",
              "ephemeral": true
            }
          }
        }
      }
    }
  }
