type: confdb-schema
authority-id: <YOUR_ACCOUNT_ID>
account-id: <YOUR_ACCOUNT_ID>
name: system-stats
revision: "11"
timestamp: <TIMESTAMP>
views:
  monitor:
    rules:
      - request: "data.{field}"
        storage: "stats.{field}"
        access: read-write
body: |-
  {
    "storage": {
      "schema": {
        "stats": {
          "schema": {
            "cpu-utilization-percent": {
              "type": "int",
              "min": 0,
              "max": 100,
              "ephemeral": true
            },
            "ram-utilization-percent": {
              "type": "int",
              "min": 0,
              "max": 100,
              "ephemeral": true
            },
            "rfs-partition-free-percent": {
              "type": "int",
              "min": 0,
              "max": 100,
              "ephemeral": true
            },
            "last-updated": {
              "type": "string",
              "ephemeral": true
            }
          }
        }
      }
    }
  }
